### ISSUE TITLE
roslaunch Python arg substitution finds wrong package folder path/xacro executable?

### ISSUE THREAD

**Issue by skohlbr** [ros/xacro#190] opened 2018-08-17 13:08 UTC
I've encountered an issue with using Python arg substitution together with using xacro as described in detail [here on ROS Answers](https://answers.ros.org/question/299232/roslaunch-python-arg-substitution-finds-wrong-package-folder-path/). It leads to only the deprecated `xacro.py` executable being found when using Python arg substitution, while a regular `find` in a launch file finds the `xacro` executable. This probably goes deeper beyond xacro, but @gavanderhoorn suggested posting here first ;)

**Comment by rhaschke** [comment] 2018-08-17 15:01
This is actually intended behaviour for ROS substitution args. I stumbled over this some years ago as well. However I couldn't find the conversation with @dirk-thomas anymore.
The key is, that `$(find pkg)` is not self-contained, but considers the context (stuff after the closing bracket) as well for search. For this reason, `$(find xacro)/xacro` returns a different path than `$(eval find('xacro') + '/xacro')`

**Closed as completed by rhaschke** 2018-08-17 15:01 UTC

**Comment by guihomework** [comment] 2018-08-17 16:19
for reference, this was the comment I think 
https://github.com/ros/xacro/issues/141#issuecomment-238941145

**Comment by skohlbr** [comment] 2018-08-17 22:10
Thanks for the explanation. So if I understand that right, if I want to use Python substitution args in a launch file, there is no way to get to the non-deprecated `xacro` executable?

**Comment by rhaschke** [comment] 2018-08-20 06:52
>  if I want to use Python substitution args in a launch file, there is no way to get to the non-deprecated xacro executable?

If you insist:
`$(eval find('xacro') + '/../../lib/xacro/xacro --inorder '`
